[simulation]
fix_benchmark = false
risk_aversion_confidence_level = 0.8
#input_data_CC = "base-input-data/RIDM-case-study-CC"
input_data = "ExperimentData/TYNDP/Outputs/tulipa_input_north_sea_2026_2030"
input_data_CC = "ExperimentData/TYNDP/Outputs/tulipa_input_north_sea_2026_2030"
#input_data = "base-input-data/RIDM-case-study"
fix_level_storage = false
solvers = ["Gurobi"]
seeds = 2
risk_aversion_weight_lambda = 0.1
scenario_data = "create-scenarios"
representative_periods = [12]
run_benchmark = false
scenarios_starting_set_sizes = [5]
number_of_scenarios = 5

[clustering]
heuristic_distance = false
use_ratio = false
