[simulation]
solvers = ["Gurobi"]
run_benchmark = true
risk_aversion_confidence_level = 0.7
risk_aversion_weight_lambda = 0.3
input_data = "base-input-data/RIDM-case-study"
number_of_scenarios = 30
representative_periods = []
rasra_size_of_j = 15
fix_level_storage = true

[clustering]
heuristic_distance = false
use_ratio = false
